general_settings:
  master_key: passbolt://13933493-22a2-4075-9d80-b14ec53f6e92/custom_fields/LITELLM_MASTER_KEY   # used to control access to the proxy

litellm_settings:
  drop_params: True
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  callbacks: ["langfuse"]
  redact_user_api_key_info: true

model_list:
# openai model list: https://docs.litellm.ai/docs/providers/openai#openai-chat-completion-models
  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-4.1-mini
    litellm_params:
      model: openai/gpt-4.1-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-4.1-nano
    litellm_params:
      model: openai/gpt-4.1-nano
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: o4-mini
    litellm_params:
      model: openai/o4-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: o3-mini
    litellm_params:
      model: openai/o3-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: o3
    litellm_params:
      model: openai/o3
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: o1-mini
    litellm_params:
      model: openai/o1-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-4-turbo
    litellm_params:
      model: openai/gpt-4-turbo
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4
      api_key: "os.environ/OPENAI_API_KEY"
# TURBO-16
  - model_name: gpt-5
    litellm_params:
      model: openai/gpt-5
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-5-pro
    litellm_params:
      model: openai/gpt-5-pro
      api_key: "os.environ/OPENAI_API_KEY"


# https://docs.litellm.ai/docs/providers/anthropic#supported-models
  - model_name: claude-opus-4
    litellm_params:
      model: anthropic/claude-opus-4-20250514
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-sonnet-4
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3.7
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-5-sonnet-20240620
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-haiku
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-opus
    litellm_params:
      model: anthropic/claude-3-opus-20240229
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-5-sonnet-20240620
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-2.1
    litellm_params:
      model: anthropic/claude-2.1
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-2
    litellm_params:
      model: anthropic/claude-2
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-instant-1.2
    litellm_params:
      model: anthropic/claude-instant-1.2
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-instant-1
    litellm_params:
      model: anthropic/claude-instant-1
      api_key: "os.environ/ANTHROPIC_API_KEY"

# mistral model list: https://docs.mistral.ai/getting-started/models/models_overview/
  - model_name: magistral-medium-latest
    litellm_params:
      model: mistral/magistral-medium-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: magistral-small-latest
    litellm_params:
      model: mistral/magistral-small-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-medium-latest
    litellm_params:
      model: mistral/mistral-medium-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-large-latest
    litellm_params:
      model: mistral/mistral-large-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: pixtral-large-latest
    litellm_params:
      model: mistral/pixtral-large-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-moderation-latest
    litellm_params:
      model: mistral/mistral-moderation-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: ministral-3b-latest
    litellm_params:
      model: mistral/ministral-3b-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: ministral-8b-latest
    litellm_params:
      model: mistral/ministral-8b-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: open-mistral-nemo
    litellm_params:
      model: mistral/open-mistral-nemo
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-small-latest
    litellm_params:
      model: mistral/mistral-small-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: devstral-small-latest
    litellm_params:
      model: mistral/devstral-small-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: devstral-medium-latest
    litellm_params:
      model: mistral/devstral-medium-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-saba-latest
    litellm_params:
      model: mistral/mistral-saba-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: codestral-latest
    litellm_params:
      model: mistral/codestral-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-ocr-latest
    litellm_params:
      model: mistral/mistral-ocr-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: voxtral-small-latest
    litellm_params:
      model: mistral/voxtral-small-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: voxtral-mini-latest
    litellm_params:
      model: mistral/voxtral-mini-latest
      api_key: "os.environ/MISTRAL_API_KEY"

# https://docs.litellm.ai/docs/providers/jina_ai // https://jina.ai?sui=reranker
  - model_name: jina-reranker-v2-base-multilingual
    litellm_params:
      model: jina_ai/jina-reranker-v2-base-multilingual
      api_key: os.environ/JINA_AI_API_KEY

# https://ai.google.dev/gemini-api/docs/models
#  - model_name: 
#    litellm_params:
#      model: gemini/
#      api_key: os.environ/GEMINI_API_KEY

  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-2.5-flash-lite
    litellm_params:
      model: gemini/gemini-2.5-flash-lite
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash-lite
    litellm_params:
      model: gemini/gemini-2.0-flash-lite
      api_key: os.environ/GEMINI_API_KEY
  - model_name: imagen-4.0-generate-preview-06-06
    litellm_params:
      model: gemini/imagen-4.0-generate-preview-06-06
      api_key: os.environ/GEMINI_API_KEY
  - model_name: imagen-4.0-ultra-generate-preview-06-06
    litellm_params:
      model: gemini/imagen-4.0-ultra-generate-preview-06-06
      api_key: os.environ/GEMINI_API_KEY
  - model_name: imagen-3.0-generate-002
    litellm_params:
      model: gemini/imagen-3.0-generate-002
      api_key: os.environ/GEMINI_API_KEY
  - model_name: veo-3.0-generate-preview
    litellm_params:
      model: gemini/veo-3.0-generate-preview
      api_key: os.environ/GEMINI_API_KEY
  - model_name: veo-2.0-generate-001
    litellm_params:
      model: gemini/veo-2.0-generate-001
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-live-2.5-flash-preview
    litellm_params:
      model: gemini/gemini-live-2.5-flash-preview
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash-live-001
    litellm_params:
      model: gemini/gemini-2.0-flash-live-001
      api_key: os.environ/GEMINI_API_KEY
